add_newline = false
# A minimal left prompt (Terminal.app compatible)
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$raku$rlang$red$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$container$shell"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[>](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = "âŽ‡ "

[aws]
format = '[$symbol(profile: "$profile" )(\\(region: $region\\) )]($style)'
disabled = true
style = 'bold blue'
symbol = "aws "

[golang]
format = '[go ](bold cyan)'
symbol = "go "

[kubernetes]
symbol = 'k8s '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \\($namespace\\))]($style) '
# contexts = [
#   { context_pattern = "arn:aws:eks:region:account:cluster/cluster-name", style = "green", context_alias = "alias", symbol = "k8s " },
# ]

[docker_context]
disabled = true

[ruby]
disabled = true
detect_files = []
detect_folders = []
detect_extensions = []

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"